<?php

include("../settings.php");
//



if ($_SERVER["REQUEST_METHOD"] == "POST")
{


	if($_GET["action"]=="save")
	{	
		if($_POST["TYPE"]=="1")
		{
			foreach ($_POST as $name => $value) {
			   //echo $name; // email, for example
			   //echo $value; // the same as echo $_POST['email'], in this case



				$add = oci_parse($ORACLEconnection, "INSERT INTO HAKASAPLAB (TYPE,BREAKDOWNNUM,CREATEDAT,COL,VAL) VALUES ('".strip_tags($_POST["TYPE"])."','".strip_tags($_POST["BREAKDOWNNUM"])."',to_date('".date("d.m.Y H:i:s")."','DD.MM.YYYY HH24:MI:SS'),'".$name."','".$value."')"); 
				oci_execute($add);


			}

		}


		else if($_POST["TYPE"]=="2")
		{
			foreach ($_POST as $name => $value) {
			   //echo $name; // email, for example
			   //echo $value; // the same as echo $_POST['email'], in this case



			$add = oci_parse($ORACLEconnection, "INSERT INTO HAKASAPLAB (TYPE,BREAKDOWNNUM,CREATEDAT,COL,VAL) VALUES ('".strip_tags($_POST["TYPE"])."','".strip_tags($_POST["BREAKDOWNNUM"])."',to_date('".date("d.m.Y H:i:s")."','DD.MM.YYYY HH24:MI:SS','".$name."','".$value."'))"); 
			oci_execute($add);
			if(oci_num_rows($add)>0)
			{
				echo "true";
			}
		}

			/*
			$add = oci_parse($ORACLEconnection, "INSERT INTO HAKLAB (TYPE,BREAKDOWNNUM,CREATEDAT,MAKINACALISMAYERI,CALISMASAATI,CALISMADEVRI,DIYAFRAMAYARI,URUNDEGIRISBAS,AGIRFAZCIKISBASINC,HAFIFFAZCIKISBASINC,DESARJ,KISMIDESARJSURESI,TAMBURACMAVALFACSURESI,TAMISSUBAS,TAMBURKAPATMAVALFSURESI,DEKVIBRASYONDEGERI,SEPVIBRASYONDEGERI,TAMDESARJSURESI,URUNDEGISURESI,TAMBURACMAVALFACSURESI2,TAMSIZSUR,TAMISSUBAS2,DEKVIBRASYONDEGERI2,SEPVIBRASYONDEGERI2,SEPISLENENURUN,URUNFAZYAG,URUNFAZSU,URUNFAZTORTU,URUNORANLARIDURUMU,URUNISLEMESICAKLIK,MUSTERIURUNPARAMETRELERI,VISKOZITEBILGISI,PARTIKULBOYUTU,POMPA,POMPATIPI,POMPAMARKAMODEL,POMPADASURUCU,POMPAMAKSIMUMDEBISI,CALISMAFREKANSI,URUNBESTANKKARISTIRICI,ISITICIVARMIYOKMU,DEKBESDEBIMIK,BOSTAAKIM,URUNDEAKIM,RANDIMANBILGISI,HAMZEYTINPIRINAYAGORANI,SEPARATORSUCIKSU,SEPARATORSUCIKYAG,SEPARATORSUCIKTORTU,PIRINAKALINTIYAGORANI,SEPARATORYAGCIKYAG,SEPARATORYAGCIKSU,SEPARATORYAGCIKTORTU,SOZLESME,ACIKLAMALAR) VALUES ('".strip_tags($_POST["TYPE"])."','".strip_tags($_POST["BREAKDOWNNUM"])."',to_date('".date("d.m.Y H:i:s")."','DD.MM.YYYY HH24:MI:SS'),'".strip_tags($_POST["MAKINACALISMAYERI"])."','".strip_tags($_POST["CALISMASAATI"])."','".strip_tags($_POST["CALISMADEVRI"])."','".strip_tags($_POST["DIYAFRAMAYARI"])."','".strip_tags($_POST["URUNDEGIRISBAS"])."','".strip_tags($_POST["AGIRFAZCIKISBASINC"])."','".strip_tags($_POST["HAFIFFAZCIKISBASINC"])."','".strip_tags($_POST["DESARJ"])."','".strip_tags($_POST["KISMIDESARJSURESI"])."','".strip_tags($_POST["TAMBURACMAVALFACSURESI"])."','".strip_tags($_POST["TAMISSUBAS"])."','".strip_tags($_POST["TAMBURKAPATMAVALFSURESI"])."','".strip_tags($_POST["DEKVIBRASYONDEGERI"])."','".strip_tags($_POST["SEPVIBRASYONDEGERI"])."','".strip_tags($_POST["TAMDESARJSURESI"])."','".strip_tags($_POST["URUNDEGISURESI"])."','".strip_tags($_POST["TAMBURACMAVALFACSURESI2"])."','".strip_tags($_POST["TAMSIZSUR"])."','".strip_tags($_POST["TAMISSUBAS2"])."','".strip_tags($_POST["DEKVIBRASYONDEGERI2"])."','".strip_tags($_POST["SEPVIBRASYONDEGERI2"])."','".strip_tags($_POST["SEPISLENENURUN"])."','".strip_tags($_POST["URUNFAZYAG"])."','".strip_tags($_POST["URUNFAZSU"])."','".strip_tags($_POST["URUNFAZTORTU"])."','".strip_tags($_POST["URUNORANLARIDURUMU"])."','".strip_tags($_POST["URUNISLEMESICAKLIK"])."','".strip_tags($_POST["MUSTERIURUNPARAMETRELERI"])."','".strip_tags($_POST["VISKOZITEBILGISI"])."','".strip_tags($_POST["PARTIKULBOYUTU"])."','".strip_tags($_POST["POMPA"])."','".strip_tags($_POST["POMPATIPI"])."','".strip_tags($_POST["POMPAMARKAMODEL"])."','".strip_tags($_POST["POMPADASURUCU"])."','".strip_tags($_POST["POMPAMAKSIMUMDEBISI"])."','".strip_tags($_POST["CALISMAFREKANSI"])."','".strip_tags($_POST["URUNBESTANKKARISTIRICI"])."','".strip_tags($_POST["ISITICIVARMIYOKMU"])."','".strip_tags($_POST["DEKBESDEBIMIK"])."','".strip_tags($_POST["BOSTAAKIM"])."','".strip_tags($_POST["URUNDEAKIM"])."','".strip_tags($_POST["RANDIMANBILGISI"])."','".strip_tags($_POST["HAMZEYTINPIRINAYAGORANI"])."','".strip_tags($_POST["SEPARATORSUCIKSU"])."','".strip_tags($_POST["SEPARATORSUCIKYAG"])."','".strip_tags($_POST["SEPARATORSUCIKTORTU"])."','".strip_tags($_POST["PIRINAKALINTIYAGORANI"])."','".strip_tags($_POST["SEPARATORYAGCIKYAG"])."','".strip_tags($_POST["SEPARATORYAGCIKSU"])."','".strip_tags($_POST["SEPARATORYAGCIKTORTU"])."','".strip_tags($_POST["SOZLESME"])."','".strip_tags($_POST["ACIKLAMALAR"])."')"); 
			oci_execute($add);
			if(oci_num_rows($add)>0)
			{

				echo "true";
			}
			*/
		}
		else if($_POST["TYPE"]=="3")
		{
			$add = oci_parse($ORACLEconnection, "INSERT INTO HAKLAB (TYPE,BREAKDOWNNUM,CREATEDAT,MODEL,SERINUMARASI,SIVICIKISKAPAKAYARI,FAZ,BEKAYARI,MOTOR,TAMBURDEVRIYUZDE,TAMBURDEVRIRPM,KAYISKASNAKDIFHIZ,BESLEMEBORUSUSEVIYESI,SUBESLEMEDEBISI,ALTSINIRDIFHIZRPM,USTSINIRDIFHIZRPM,AKTUELDIFHIZRPM,TAMBURDEVRIYUZDE2,TAMBURDEVRIRPM2,HELEZONMOTORHIZIRPM,AKTUELTORKDEGERI,REGULASYONBASLANGICTORKU,DEKANTORUKAPATMATORKU,VIBRASYONDEGERI,BESLEMEBORUSUSEVIYESI2,YATAKSICAKLIKURUN,YATAKSICAKLIKSANZUMAN,SUBESLEMEDEBISI2,NUMUNE,NUMUNEALANMADI,OLIVETYPE,ZEYTINYORESI,ZEYTINDEKIYAG,MALAKSORKARISMA,MALAKSORHAMURSIC,DEKANTORYAGCIKSIC,SEPARATORYAGCIKSIC,POMPA,POMPATIPI,POMPAMARKAMODEL,POLPOMPADASURUCU,POMPAMAKSIMUMDEBISI,CALISMAFREKANSI,CALISMAYUZDESI,DEBIMETREVARMI,DEKBESDEBIMIK,TAMBURMOTORUHZ,TAMBURMOTORUKW,TAMBURMOTORUAMPER,HELEZONMOTORUHZ,HELEZONMOTORUKW,HELEZONMOTORUAMPER,KIRICIAKIMI,RANDIMANBILGISI,DEKANTORYAG,DEKANTORSU,DEKANTORTORTU,DEKGIRNEM,DEKGIRPY,DEKGIRKPY,DEKCIKNEM,DEKCIKPY,DEKCIKKPY,KARASUDAYAGORANI,SOZLESME,MUSPERBILGILERI,ACIKLAMALAR) VALUES ('".strip_tags($_POST["TYPE"])."','".strip_tags($_POST["BREAKDOWNNUM"])."',to_date('".date("d.m.Y H:i:s")."','DD.MM.YYYY HH24:MI:SS'),'".strip_tags($_POST["MODEL"])."','".strip_tags($_POST["SERINUMARASI"])."','".strip_tags($_POST["SIVICIKISKAPAKAYARI"])."','".strip_tags($_POST["FAZ"])."','".strip_tags($_POST["BEKAYARI"])."','".strip_tags($_POST["MOTOR"])."','".strip_tags($_POST["TAMBURDEVRIYUZDE"])."','".strip_tags($_POST["TAMBURDEVRIRPM"])."','".strip_tags($_POST["KAYISKASNAKDIFHIZ"])."','".strip_tags($_POST["BESLEMEBORUSUSEVIYESI"])."','".strip_tags($_POST["SUBESLEMEDEBISI"])."','".strip_tags($_POST["ALTSINIRDIFHIZRPM"])."','".strip_tags($_POST["USTSINIRDIFHIZRPM"])."','".strip_tags($_POST["AKTUELDIFHIZRPM"])."','".strip_tags($_POST["TAMBURDEVRIYUZDE2"])."','".strip_tags($_POST["TAMBURDEVRIRPM2"])."','".strip_tags($_POST["HELEZONMOTORHIZIRPM"])."','".strip_tags($_POST["AKTUELTORKDEGERI"])."','".strip_tags($_POST["REGULASYONBASLANGICTORKU"])."','".strip_tags($_POST["DEKANTORUKAPATMATORKU"])."','".strip_tags($_POST["VIBRASYONDEGERI"])."','".strip_tags($_POST["BESLEMEBORUSUSEVIYESI2"])."','".strip_tags($_POST["YATAKSICAKLIKURUN"])."','".strip_tags($_POST["YATAKSICAKLIKSANZUMAN"])."','".strip_tags($_POST["SUBESLEMEDEBISI2"])."','".strip_tags($_POST["NUMUNE"])."','".strip_tags($_POST["NUMUNEALANMADI"])."','".strip_tags($_POST["OLIVETYPE"])."','".strip_tags($_POST["ZEYTINYORESI"])."','".strip_tags($_POST["ZEYTINDEKIYAG"])."','".strip_tags($_POST["MALAKSORKARISMA"])."','".strip_tags($_POST["MALAKSORHAMURSIC"])."','".strip_tags($_POST["DEKANTORYAGCIKSIC"])."','".strip_tags($_POST["SEPARATORYAGCIKSIC"])."','".strip_tags($_POST["POMPA"])."','".strip_tags($_POST["POMPATIPI"])."','".strip_tags($_POST["POMPAMARKAMODEL"])."','".strip_tags($_POST["POLPOMPADASURUCU"])."','".strip_tags($_POST["POMPAMAKSIMUMDEBISI"])."','".strip_tags($_POST["CALISMAFREKANSI"])."','".strip_tags($_POST["CALISMAYUZDESI"])."','".strip_tags($_POST["DEBIMETREVARMI"])."','".strip_tags($_POST["DEKBESDEBIMIK"])."','".strip_tags($_POST["TAMBURMOTORUHZ"])."','".strip_tags($_POST["TAMBURMOTORUKW"])."','".strip_tags($_POST["TAMBURMOTORUAMPER"])."','".strip_tags($_POST["HELEZONMOTORUHZ"])."','".strip_tags($_POST["HELEZONMOTORUKW"])."','".strip_tags($_POST["HELEZONMOTORUAMPER"])."','".strip_tags($_POST["KIRICIAKIMI"])."','".strip_tags($_POST["RANDIMANBILGISI"])."','".strip_tags($_POST["DEKANTORYAG"])."','".strip_tags($_POST["DEKANTORSU"])."','".strip_tags($_POST["DEKANTORTORTU"])."','".strip_tags($_POST["DEKGIRNEM"])."','".strip_tags($_POST["DEKGIRPY"])."','".strip_tags($_POST["DEKGIRKPY"])."','".strip_tags($_POST["DEKCIKNEM"])."','".strip_tags($_POST["DEKCIKPY"])."','".strip_tags($_POST["DEKCIKKPY"])."','".strip_tags($_POST["KARASUDAYAGORANI"])."','".strip_tags($_POST["SOZLESME"])."','".strip_tags($_POST["MUSPERBILGILERI"])."','".strip_tags($_POST["ACIKLAMALAR"])."')"); 
			oci_execute($add);
			if(oci_num_rows($add)>0)
			{
				
				echo "true";
			}
		}	
	
		else if($_POST["TYPE"]=="4")
		{
			$add = oci_parse($ORACLEconnection, "INSERT INTO HAKLAB (TYPE,BREAKDOWNNUM,CREATEDAT,VIDALISERINO,CALISMASAATI,YUZDEVIDAHIZI,ANLIKVIDAHIZI,KATICIKISBASINC,ANLIKBASINC,ANLIKTORK,SIRKULASYONPOMPA,YIKAMADONGUSU,YIKAMASURESI,VIDALIPRESCEKGUCKW,VIDALIPRESCEKAKIM,BESCAMURTIPI,CAMURKURUMADDE,CAMURPOMPADEBISI,POLMARKATURBILGISI,POLIMERHAZIRORANI,POLIMERDEBISI,PRESCIKISKEK,PRESCIKISSENTRAT,SOZLESME,ACIKLAMALAR) VALUES ('".strip_tags($_POST["TYPE"])."','".strip_tags($_POST["BREAKDOWNNUM"])."',to_date('".date("d.m.Y H:i:s")."','DD.MM.YYYY HH24:MI:SS'),'".strip_tags($_POST["VIDALISERINO"])."','".strip_tags($_POST["CALISMASAATI"])."','".strip_tags($_POST["YUZDEVIDAHIZI"])."','".strip_tags($_POST["YUZDEVIDAHIZI"])."','".strip_tags($_POST["KATICIKISBASINC"])."','".strip_tags($_POST["ANLIKBASINC"])."','".strip_tags($_POST["ANLIKTORK"])."','".strip_tags($_POST["SIRKULASYONPOMPA"])."','".strip_tags($_POST["YIKAMADONGUSU"])."','".strip_tags($_POST["YIKAMASURESI"])."','".strip_tags($_POST["VIDALIPRESCEKGUCKW"])."','".strip_tags($_POST["VIDALIPRESCEKAKIM"])."','".strip_tags($_POST["BESCAMURTIPI"])."','".strip_tags($_POST["CAMURKURUMADDE"])."','".strip_tags($_POST["CAMURPOMPADEBISI"])."','".strip_tags($_POST["POLMARKATURBILGISI"])."','".strip_tags($_POST["POLIMERHAZIRORANI"])."','".strip_tags($_POST["POLIMERDEBISI"])."','".strip_tags($_POST["PRESCIKISKEK"])."','".strip_tags($_POST["PRESCIKISSENTRAT"])."','".strip_tags($_POST["SOZLESME"])."','".strip_tags($_POST["ACIKLAMALAR"])."')"); 
			oci_execute($add);
			if(oci_num_rows($add)>0)
			{
				
				echo "true";
			}
		}
		else if($_POST["TYPE"]=="5")
		{
			$add = oci_parse($ORACLEconnection, "INSERT INTO HAKLAB (TYPE,BREAKDOWNNUM,CREATEDAT,BLOWERSERIALNUM,BLOWERCALISMADEBISI,SOZLESME,ACIKLAMALAR) VALUES ('".strip_tags($_POST["TYPE"])."','".strip_tags($_POST["BREAKDOWNNUM"])."',to_date('".date("d.m.Y H:i:s")."','DD.MM.YYYY HH24:MI:SS'),'".strip_tags($_POST["BLOWERSERIALNUM"])."','".strip_tags($_POST["BLOWERCALISMADEBISI"])."','".strip_tags($_POST["SOZLESME"])."','".strip_tags($_POST["ACIKLAMALAR"])."')"); 
			oci_execute($add);
			if(oci_num_rows($add)>0)
			{

				echo "true";
			}
		}

		

	}

	


if($_GET["action"]=="update")
		{
			if($_POST["TYPE"]=="1")
			{
				$add = oci_parse($ORACLEconnection, "UPDATE HAKLAB SET MODEL='".strip_tags($_POST["MODEL"])."',SERINUMARASI='".strip_tags($_POST["SERINUMARASI"])."',CALISMASAATI='".strip_tags($_POST["CALISMASAATI"])."',CALISMADEVRI='".strip_tags($_POST["CALISMADEVRI"])."',FAZ='".strip_tags($_POST["FAZ"])."',MOTOR='".strip_tags($_POST["MOTOR"])."',TAMBURDEVRIYUZDE='".strip_tags($_POST["TAMBURDEVRIYUZDE"])."',KAYISKASNAKDIFHIZ='".strip_tags($_POST["KAYISKASNAKDIFHIZ"])."',BESLEMEBORUSUSEVIYESI='".strip_tags($_POST["BESLEMEBORUSUSEVIYESI"])."',BEKAYARI='".strip_tags($_POST["BEKAYARI"])."',ALTSINIRDIFHIZRPM='".strip_tags($_POST["ALTSINIRDIFHIZRPM"])."',USTSINIRDIFHIZRPM='".strip_tags($_POST["USTSINIRDIFHIZRPM"])."',AKTUELDIFHIZRPM='".strip_tags($_POST["AKTUELDIFHIZRPM"])."',HELEZONMOTORHIZIRPM='".strip_tags($_POST["HELEZONMOTORHIZIRPM"])."',AKTUELTORKDEGERI='".strip_tags($_POST["AKTUELTORKDEGERI"])."',REGULASYONBASLANGICTORKU='".strip_tags($_POST["REGULASYONBASLANGICTORKU"])."',POMPALIKAPATMATORKU='".strip_tags($_POST["POMPALIKAPATMATORKU"])."',DEKANTORUKAPATMATORKU='".strip_tags($_POST["DEKANTORUKAPATMATORKU"])."',VIBRASYONDEGERI='".strip_tags($_POST["VIBRASYONDEGERI"])."',BESLEMEBORUSUSEVIYESIIKI='".strip_tags($_POST["BESLEMEBORUSUSEVIYESIIKI"])."',YATAKSICAKLIKURUN='".strip_tags($_POST["YATAKSICAKLIKURUN"])."',YATAKSICAKLIKSANZUMAN='".strip_tags($_POST["YATAKSICAKLIKSANZUMAN"])."',SIVICIKISKAPAKAYARI='".strip_tags($_POST["SIVICIKISKAPAKAYARI"])."',TAMBURDEVRIIKI='".strip_tags($_POST["TAMBURDEVRIIKI"])."',BESLEMEBORUSUSEVIYESIUC='".strip_tags($_POST["BESLEMEBORUSUSEVIYESIUC"])."',SUBESLEMEDEBISI='".strip_tags($_POST["SUBESLEMEDEBISI"])."',MAXHELEZONASINMA='".strip_tags($_POST["MAXHELEZONASINMA"])."',GENELPROSESBILGISI='".strip_tags($_POST["GENELPROSESBILGISI"])."',EKIPMANABESLENENURUN='".strip_tags($_POST["EKIPMANABESLENENURUN"])."',TOPLAMKATIMADDE='".strip_tags($_POST["TOPLAMKATIMADDE"])."',MUSPERBILGILERI='".strip_tags($_POST["MUSPERBILGILERI"])."',NUMUNE= '".strip_tags($_POST["NUMUNE"])."',NUMUNEALANMADI='".strip_tags($_POST["NUMUNEALANMADI"])."',SANTSONHACORANKATI='".strip_tags($_POST["SANTSONHACORANKATI"])."',SANTSONHACORANSIVI='".strip_tags($_POST["SANTSONHACORANSIVI"])."',SANTSONHACORANYAG='".strip_tags($_POST["SANTSONHACORANYAG"])."',PHSEVIYESI='".strip_tags($_POST["PHSEVIYESI"])."',YOGUNLUGU='".strip_tags($_POST["YOGUNLUGU"])."',ASKIDAKATIMADDE='".strip_tags($_POST["ASKIDAKATIMADDE"])."',ISLEMESICAKLIGI='".strip_tags($_POST["ISLEMESICAKLIGI"])."',ORGANIKMADDEMIKTARI='".strip_tags($_POST["ORGANIKMADDEMIKTARI"])."',CAMURHACIMINDEKSI='".strip_tags($_POST["CAMURHACIMINDEKSI"])."',DIGERBILGILER='".strip_tags($_POST["DIGERBILGILER"])."',POMPA='".strip_tags($_POST["POMPA"])."',POMPATIPI='".strip_tags($_POST["POMPATIPI"])."',POMPAMARKAMODEL='".strip_tags($_POST["POMPAMARKAMODEL"])."',POMPADASURUCU='".strip_tags($_POST["POMPADASURUCU"])."',POMPAMAKSIMUMDEBISI='".strip_tags($_POST["POMPAMAKSIMUMDEBISI"])."',CALISMAFREKANSI='".strip_tags($_POST["CALISMAFREKANSI"])."',CALISMAYUZDESI='".strip_tags($_POST["CALISMAYUZDESI"])."',DEBIMETREVARMI='".strip_tags($_POST["DEBIMETREVARMI"])."',DEKBESDEBIMIK='".strip_tags($_POST["DEKBESDEBIMIK"])."',POLIMER='".strip_tags($_POST["POLIMER"])."',POLPOMPA='".strip_tags($_POST["POLPOMPA"])."',POLPOMPATIPI='".strip_tags($_POST["POLPOMPATIPI"])."',POLPOMPAMARKAMODEL='".strip_tags($_POST["POLPOMPAMARKAMODEL"])."',POLPOMPADASURUCU='".strip_tags($_POST["POLPOMPADASURUCU"])."',POLPOMPAMAXDEBI='".strip_tags($_POST["POLPOMPAMAXDEBI"])."',POLCALISMAFREKANSI='".strip_tags($_POST["POLCALISMAFREKANSI"])."',POLCALISMAYUZDESI='".strip_tags($_POST["POLCALISMAYUZDESI"])."',POLDEBIMETREVARMI='".strip_tags($_POST["POLDEBIMETREVARMI"])."',POLDEKBESDEBIMIK='".strip_tags($_POST["POLDEKBESDEBIMIK"])."',POLTANKKAP='".strip_tags($_POST["POLTANKKAP"])."',KULPOLMARKAKOD='".strip_tags($_POST["KULPOLMARKAKOD"])."',POLHAZIRORANI='".strip_tags($_POST["POLHAZIRORANI"])."',POLSARF='".strip_tags($_POST["POLSARF"])."',TAMBURMOTORUHZ='".strip_tags($_POST["TAMBURMOTORUHZ"])."',TAMBURMOTORUKW='".strip_tags($_POST["TAMBURMOTORUKW"])."',TAMBURMOTORUAMPER='".strip_tags($_POST["TAMBURMOTORUAMPER"])."',HELEZONMOTORUHZ='".strip_tags($_POST["HELEZONMOTORUHZ"])."',HELEZONMOTORUKW='".strip_tags($_POST["HELEZONMOTORUKW"])."',HELEZONMOTORUAMPER='".strip_tags($_POST["HELEZONMOTORUAMPER"])."',DEKKEKCIKIS='".strip_tags($_POST["DEKKEKCIKIS"])."',MUSDEKKEKCIKIS='".strip_tags($_POST["MUSDEKKEKCIKIS"])."',DEKSENTRATCIKIS='".strip_tags($_POST["DEKSENTRATCIKIS"])."',SENTRATHACYAG='".strip_tags($_POST["SENTRATHACYAG"])."',SENTRATHACSU='".strip_tags($_POST["SENTRATHACSU"])."',SENTRATHACTORTU='".strip_tags($_POST["SENTRATHACTORTU"])."',DEKANTORYAG='".strip_tags($_POST["DEKANTORYAG"])."',DEKANTORSU='".strip_tags($_POST["DEKANTORSU"])."',DEKANTORTORTU='".strip_tags($_POST["DEKANTORTORTU"])."',SOZLESME='".strip_tags($_POST["SOZLESME"])."',ACIKLAMALAR='".strip_tags($_POST["ACIKLAMALAR"])."' WHERE CREATEDAT=to_date('".strip_tags($_POST["CREATEDAT"])."','DD.MM.YYYY HH24:MI:SS') AND BREAKDOWNNUM='".strip_tags($_POST["BREAKDOWNNUM"])."'"); 
			oci_execute($add);
			if(oci_num_rows($add)>0)
			{
				echo "true";
			}
			}

			if($_POST["TYPE"]=="2")
			{
				$add = oci_parse($ORACLEconnection, "UPDATE HAKLAB SET MAKINACALISMAYERI='".strip_tags($_POST["MAKINACALISMAYERI"])."',CALISMASAATI='".strip_tags($_POST["CALISMASAATI"])."',CALISMADEVRI='".strip_tags($_POST["CALISMADEVRI"])."',DIYAFRAMAYARI='".strip_tags($_POST["DIYAFRAMAYARI"])."',URUNDEGIRISBAS='".strip_tags($_POST["URUNDEGIRISBAS"])."',AGIRFAZCIKISBASINC='".strip_tags($_POST["AGIRFAZCIKISBASINC"])."',HAFIFFAZCIKISBASINC='".strip_tags($_POST["HAFIFFAZCIKISBASINC"])."',DESARJ='".strip_tags($_POST["DESARJ"])."',KISMIDESARJSURESI='".strip_tags($_POST["KISMIDESARJSURESI"])."',TAMBURACMAVALFACSURESI='".strip_tags($_POST["TAMBURACMAVALFACSURESI"])."',TAMISSUBAS='".strip_tags($_POST["TAMISSUBAS"])."',TAMBURKAPATMAVALFSURESI='".strip_tags($_POST["TAMBURKAPATMAVALFSURESI"])."',DEKVIBRASYONDEGERI='".strip_tags($_POST["DEKVIBRASYONDEGERI"])."',SEPVIBRASYONDEGERI='".strip_tags($_POST["SEPVIBRASYONDEGERI"])."',TAMDESARJSURESI='".strip_tags($_POST["TAMDESARJSURESI"])."',URUNDEGISURESI='".strip_tags($_POST["URUNDEGISURESI"])."',TAMBURACMAVALFACSURESI2='".strip_tags($_POST["TAMBURACMAVALFACSURESI2"])."',TAMSIZSUR='".strip_tags($_POST["TAMSIZSUR"])."',TAMISSUBAS2='".strip_tags($_POST["TAMISSUBAS2"])."',DEKVIBRASYONDEGERI2='".strip_tags($_POST["DEKVIBRASYONDEGERI2"])."',SEPVIBRASYONDEGERI2='".strip_tags($_POST["SEPVIBRASYONDEGERI2"])."',SEPISLENENURUN='".strip_tags($_POST["SEPISLENENURUN"])."',URUNFAZYAG='".strip_tags($_POST["URUNFAZYAG"])."',URUNFAZSU='".strip_tags($_POST["URUNFAZSU"])."',URUNFAZTORTU='".strip_tags($_POST["URUNFAZTORTU"])."',URUNORANLARIDURUMU='".strip_tags($_POST["URUNORANLARIDURUMU"])."',URUNISLEMESICAKLIK='".strip_tags($_POST["URUNISLEMESICAKLIK"])."',MUSTERIURUNPARAMETRELERI='".strip_tags($_POST["MUSTERIURUNPARAMETRELERI"])."',VISKOZITEBILGISI='".strip_tags($_POST["VISKOZITEBILGISI"])."',PARTIKULBOYUTU='".strip_tags($_POST["PARTIKULBOYUTU"])."',POMPA='".strip_tags($_POST["POMPA"])."',POMPATIPI='".strip_tags($_POST["POMPATIPI"])."',POMPAMARKAMODEL='".strip_tags($_POST["POMPAMARKAMODEL"])."',POMPADASURUCU='".strip_tags($_POST["POMPADASURUCU"])."',POMPAMAKSIMUMDEBISI='".strip_tags($_POST["POMPAMAKSIMUMDEBISI"])."',CALISMAFREKANSI='".strip_tags($_POST["CALISMAFREKANSI"])."',URUNBESTANKKARISTIRICI='".strip_tags($_POST["URUNBESTANKKARISTIRICI"])."',ISITICIVARMIYOKMU='".strip_tags($_POST["ISITICIVARMIYOKMU"])."',DEKBESDEBIMIK='".strip_tags($_POST["DEKBESDEBIMIK"])."',BOSTAAKIM='".strip_tags($_POST["BOSTAAKIM"])."',URUNDEAKIM='".strip_tags($_POST["URUNDEAKIM"])."',RANDIMANBILGISI='".strip_tags($_POST["RANDIMANBILGISI"])."',HAMZEYTINPIRINAYAGORANI='".strip_tags($_POST["HAMZEYTINPIRINAYAGORANI"])."',SEPARATORSUCIKSU='".strip_tags($_POST["SEPARATORSUCIKSU"])."',SEPARATORSUCIKYAG='".strip_tags($_POST["SEPARATORSUCIKYAG"])."',SEPARATORSUCIKTORTU='".strip_tags($_POST["SEPARATORSUCIKTORTU"])."',PIRINAKALINTIYAGORANI='".strip_tags($_POST["PIRINAKALINTIYAGORANI"])."',SEPARATORYAGCIKYAG='".strip_tags($_POST["SEPARATORYAGCIKYAG"])."',SEPARATORYAGCIKSU='".strip_tags($_POST["SEPARATORYAGCIKSU"])."',SEPARATORYAGCIKTORTU='".strip_tags($_POST["SEPARATORYAGCIKTORTU"])."',SOZLESME='".strip_tags($_POST["SOZLESME"])."',ACIKLAMALAR='".strip_tags($_POST["ACIKLAMALAR"])."' WHERE CREATEDAT=to_date('".strip_tags($_POST["CREATEDAT"])."','DD.MM.YYYY HH24:MI:SS') AND BREAKDOWNNUM='".strip_tags($_POST["BREAKDOWNNUM"])."'"); 
				oci_execute($add);
				if(oci_num_rows($add)>0)
				{
					echo "true";
				}
			}

			if($_POST["TYPE"]=="3")
			{
				$add = oci_parse($ORACLEconnection, "UPDATE HAKLAB SET MODEL='".strip_tags($_POST["MODEL"])."',SERINUMARASI='".strip_tags($_POST["SERINUMARASI"])."',SIVICIKISKAPAKAYARI='".strip_tags($_POST["SIVICIKISKAPAKAYARI"])."',FAZ='".strip_tags($_POST["FAZ"])."',BEKAYARI='".strip_tags($_POST["BEKAYARI"])."',MOTOR='".strip_tags($_POST["MOTOR"])."',TAMBURDEVRIYUZDE='".strip_tags($_POST["TAMBURDEVRIYUZDE"])."',TAMBURDEVRIRPM='".strip_tags($_POST["TAMBURDEVRIRPM"])."',KAYISKASNAKDIFHIZ='".strip_tags($_POST["KAYISKASNAKDIFHIZ"])."',BESLEMEBORUSUSEVIYESI='".strip_tags($_POST["BESLEMEBORUSUSEVIYESI"])."',SUBESLEMEDEBISI='".strip_tags($_POST["SUBESLEMEDEBISI"])."',ALTSINIRDIFHIZRPM='".strip_tags($_POST["ALTSINIRDIFHIZRPM"])."',USTSINIRDIFHIZRPM='".strip_tags($_POST["USTSINIRDIFHIZRPM"])."',AKTUELDIFHIZRPM='".strip_tags($_POST["AKTUELDIFHIZRPM"])."',TAMBURDEVRIYUZDE2='".strip_tags($_POST["TAMBURDEVRIYUZDE2"])."',TAMBURDEVRIRPM2='".strip_tags($_POST["TAMBURDEVRIRPM2"])."',HELEZONMOTORHIZIRPM='".strip_tags($_POST["HELEZONMOTORHIZIRPM"])."',AKTUELTORKDEGERI='".strip_tags($_POST["AKTUELTORKDEGERI"])."',REGULASYONBASLANGICTORKU='".strip_tags($_POST["REGULASYONBASLANGICTORKU"])."',DEKANTORUKAPATMATORKU='".strip_tags($_POST["DEKANTORUKAPATMATORKU"])."',VIBRASYONDEGERI='".strip_tags($_POST["VIBRASYONDEGERI"])."',BESLEMEBORUSUSEVIYESI2='".strip_tags($_POST["BESLEMEBORUSUSEVIYESI2"])."',YATAKSICAKLIKURUN='".strip_tags($_POST["YATAKSICAKLIKURUN"])."',YATAKSICAKLIKSANZUMAN='".strip_tags($_POST["YATAKSICAKLIKSANZUMAN"])."',
					SUBESLEMEDEBISI2='".strip_tags($_POST["SUBESLEMEDEBISI2"])."',NUMUNE='".strip_tags($_POST["NUMUNE"])."',NUMUNEALANMADI='".strip_tags($_POST["NUMUNEALANMADI"])."',OLIVETYPE='".strip_tags($_POST["OLIVETYPE"])."',ZEYTINYORESI='".strip_tags($_POST["ZEYTINYORESI"])."',ZEYTINDEKIYAG='".strip_tags($_POST["ZEYTINDEKIYAG"])."',MALAKSORKARISMA='".strip_tags($_POST["MALAKSORKARISMA"])."',MALAKSORHAMURSIC='".strip_tags($_POST["MALAKSORHAMURSIC"])."',DEKANTORYAGCIKSIC='".strip_tags($_POST["DEKANTORYAGCIKSIC"])."',SEPARATORYAGCIKSIC='".strip_tags($_POST["SEPARATORYAGCIKSIC"])."',POMPA='".strip_tags($_POST["POMPA"])."',POMPATIPI='".strip_tags($_POST["POMPATIPI"])."',POMPAMARKAMODEL='".strip_tags($_POST["POMPAMARKAMODEL"])."',POLPOMPADASURUCU='".strip_tags($_POST["POLPOMPADASURUCU"])."',POMPAMAKSIMUMDEBISI='".strip_tags($_POST["POMPAMAKSIMUMDEBISI"])."',CALISMAFREKANSI='".strip_tags($_POST["CALISMAFREKANSI"])."',CALISMAYUZDESI='".strip_tags($_POST["CALISMAYUZDESI"])."',DEBIMETREVARMI='".strip_tags($_POST["DEBIMETREVARMI"])."',DEKBESDEBIMIK='".strip_tags($_POST["DEKBESDEBIMIK"])."',TAMBURMOTORUHZ='".strip_tags($_POST["TAMBURMOTORUHZ"])."',TAMBURMOTORUKW='".strip_tags($_POST["TAMBURMOTORUKW"])."',TAMBURMOTORUAMPER='".strip_tags($_POST["TAMBURMOTORUAMPER"])."',HELEZONMOTORUHZ='".strip_tags($_POST["HELEZONMOTORUHZ"])."',HELEZONMOTORUKW='".strip_tags($_POST["HELEZONMOTORUKW"])."',HELEZONMOTORUAMPER='".strip_tags($_POST["HELEZONMOTORUAMPER"])."',KIRICIAKIMI='".strip_tags($_POST["KIRICIAKIMI"])."',RANDIMANBILGISI='".strip_tags($_POST["RANDIMANBILGISI"])."',DEKANTORYAG='".strip_tags($_POST["DEKANTORYAG"])."',DEKANTORSU='".strip_tags($_POST["DEKANTORSU"])."',DEKANTORTORTU='".strip_tags($_POST["DEKANTORTORTU"])."',DEKGIRNEM='".strip_tags($_POST["DEKGIRNEM"])."',DEKGIRPY='".strip_tags($_POST["DEKGIRPY"])."',DEKGIRKPY='".strip_tags($_POST["DEKGIRKPY"])."',DEKCIKNEM='".strip_tags($_POST["DEKCIKNEM"])."',DEKCIKPY='".strip_tags($_POST["DEKCIKPY"])."',DEKCIKKPY='".strip_tags($_POST["DEKCIKKPY"])."',KARASUDAYAGORANI='".strip_tags($_POST["KARASUDAYAGORANI"])."',SOZLESME='".strip_tags($_POST["SOZLESME"])."',MUSPERBILGILERI='".strip_tags($_POST["MUSPERBILGILERI"])."',ACIKLAMALAR='".strip_tags($_POST["ACIKLAMALAR"])."' WHERE CREATEDAT=to_date('".strip_tags($_POST["CREATEDAT"])."','DD.MM.YYYY HH24:MI:SS') AND BREAKDOWNNUM='".strip_tags($_POST["BREAKDOWNNUM"])."'"); 
				oci_execute($add);
				if(oci_num_rows($add)>0)
				{
					echo "true";
				}
			}


			if($_POST["TYPE"]=="4")
			{
				$add = oci_parse($ORACLEconnection, "UPDATE HAKLAB SET VIDALISERINO='".strip_tags($_POST["VIDALISERINO"])."',CALISMASAATI='".strip_tags($_POST["CALISMASAATI"])."',YUZDEVIDAHIZI='".strip_tags($_POST["YUZDEVIDAHIZI"])."',ANLIKVIDAHIZI='".strip_tags($_POST["ANLIKVIDAHIZI"])."',KATICIKISBASINC='".strip_tags($_POST["KATICIKISBASINC"])."',ANLIKBASINC='".strip_tags($_POST["ANLIKBASINC"])."',ANLIKTORK='".strip_tags($_POST["ANLIKTORK"])."',SIRKULASYONPOMPA='".strip_tags($_POST["SIRKULASYONPOMPA"])."',YIKAMADONGUSU='".strip_tags($_POST["YIKAMADONGUSU"])."',YIKAMASURESI='".strip_tags($_POST["YIKAMASURESI"])."',VIDALIPRESCEKGUCKW='".strip_tags($_POST["VIDALIPRESCEKGUCKW"])."',VIDALIPRESCEKAKIM='".strip_tags($_POST["VIDALIPRESCEKAKIM"])."',BESCAMURTIPI='".strip_tags($_POST["BESCAMURTIPI"])."',CAMURKURUMADDE='".strip_tags($_POST["CAMURKURUMADDE"])."',CAMURPOMPADEBISI='".strip_tags($_POST["CAMURPOMPADEBISI"])."',POLMARKATURBILGISI='".strip_tags($_POST["POLMARKATURBILGISI"])."',POLIMERHAZIRORANI='".strip_tags($_POST["POLIMERHAZIRORANI"])."',POLIMERDEBISI='".strip_tags($_POST["POLIMERDEBISI"])."',PRESCIKISKEK='".strip_tags($_POST["PRESCIKISKEK"])."',PRESCIKISSENTRAT='".strip_tags($_POST["PRESCIKISSENTRAT"])."',SOZLESME='".strip_tags($_POST["SOZLESME"])."',ACIKLAMALAR='".strip_tags($_POST["ACIKLAMALAR"])."' WHERE CREATEDAT=to_date('".strip_tags($_POST["CREATEDAT"])."','DD.MM.YYYY HH24:MI:SS') AND BREAKDOWNNUM='".strip_tags($_POST["BREAKDOWNNUM"])."'" ); 
				oci_execute($add);
				if(oci_num_rows($add)>0)
				{
					echo "true";
				}
			}

			if($_POST["TYPE"]=="5")
			{
				$add = oci_parse($ORACLEconnection, "UPDATE HAKLAB SET BLOWERSERIALNUM='".strip_tags($_POST["BLOWERSERIALNUM"])."',MOTORCALISMAHIZI='".strip_tags($_POST["MOTORCALISMAHIZI"])."',SOGUTUCUPOMPA='".strip_tags($_POST["SOGUTUCUPOMPA"])."',RADYOTORFANICALISMA='".strip_tags($_POST["RADYOTORFANICALISMA"])."',MOTORSOGUTMAFANLARI='".strip_tags($_POST["MOTORSOGUTMAFANLARI"])."',MANYETIKRULMEN='".strip_tags($_POST["MANYETIKRULMEN"])."',SOGUTUCUSUBASINCI='".strip_tags($_POST["SOGUTUCUSUBASINCI"])."',EMISFILTREBASINCI='".strip_tags($_POST["EMISFILTREBASINCI"])."',AGIRINISLERVW='".strip_tags($_POST["AGIRINISLERVW"])."',AGIRISNISLERWP='".strip_tags($_POST["AGIRISNISLERWP"])."',AGIRINISLERZ='".strip_tags($_POST["AGIRINISLERZ"])."',BALANSDEGERI='".strip_tags($_POST["BALANSDEGERI"])."',ABALANSSIZLIK='".strip_tags($_POST["ABALANSSIZLIK"])."',BBALANSSIZLIKDEGERI='".strip_tags($_POST["BBALANSSIZLIKDEGERI"])."',BALANSDEGERBILESKESI='".strip_tags($_POST["BALANSDEGERBILESKESI"])."',BALANSVW='".strip_tags($_POST["BALANSVW"])."',BALANSDEGERIVW='".strip_tags($_POST["BALANSDEGERIVW"])."',GOZMAKTEPEBALANS='".strip_tags($_POST["GOZMAKTEPEBALANS"])."',BLOWERCALISMADEVRI='".strip_tags($_POST["BLOWERCALISMADEVRI"])."',BLOWERCALISMADEBISI='".strip_tags($_POST["BLOWERCALISMADEBISI"])."',BLOWERORTAMSICAKLIGI='".strip_tags($_POST["BLOWERORTAMSICAKLIGI"])."',HARCANANENERGY='".strip_tags($_POST["HARCANANENERGY"])."',MOTORDEVIRSICAKLIGI='".strip_tags($_POST["MOTORDEVIRSICAKLIGI"])."',MOTORDEVIRSICAKLIGITHN='".strip_tags($_POST["MOTORDEVIRSICAKLIGITHN"])."',MOTORSICAKLIGITHO='".strip_tags($_POST["MOTORSICAKLIGITHO"])."',INTERCOOLERSICAK='".strip_tags($_POST["INTERCOOLERSICAK"])."',VFDSICAKLIGI='".strip_tags($_POST["VFDSICAKLIGI"])."',KABINICISICAKLIK='".strip_tags($_POST["KABINICISICAKLIK"])."',SOZLESME='".strip_tags($_POST["SOZLESME"])."',MUSPERBILGILERI='".strip_tags($_POST["MUSPERBILGILERI"])."',ACIKLAMALAR='".strip_tags($_POST["ACIKLAMALAR"])."' WHERE CREATEDAT=to_date('".strip_tags($_POST["CREATEDAT"])."','DD.MM.YYYY HH24:MI:SS') AND BREAKDOWNNUM='".strip_tags($_POST["BREAKDOWNNUM"])."'"); 
				oci_execute($add);
				if(oci_num_rows($add)>0)
				{
					
					echo "true";



				}
			}
		}
	if($_GET["action"]=="approve")
	{
		$add = oci_parse($ORACLEconnection, "UPDATE HAKBREAKDOWNSFORM SET HAKDEVREYEALMADURUM='1' WHERE BREAKDOWNNUM='".strip_tags($_POST["BREAKDOWNNUM"])."'"); 
		oci_execute($add);
		if(oci_num_rows($add)>0)
		{
			$add = oci_parse($ORACLEconnection, "UPDATE HAKLAB SET ONAY='1' WHERE BREAKDOWNNUM='".strip_tags($_POST["BREAKDOWNNUM"])."' AND CREATEDAT='".strip_tags($_POST["CREATEDAT"])."'"); 
			oci_execute($add);
			if(oci_num_rows($add)>0)
			{
				echo "true";
			}
		}


		//HAKBREAKDOWNSFORM

		//HAKDEVREYEALMAFORMU
	}
}








 
?>